services:
  postgres:
    image: postgres:16
    container_name: taskforge-postgres
    environment:
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforge
      POSTGRES_DB: taskforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskforge-redis
    ports:
      - "6379:6379"

  api:
    build: /apps/api
    container_name: taskforge-api
    depends_on:
      - postgres
      - redis
  
  worker:
    build: /apps/worker
    container_name: taskforge-worker
    depends_on:
      - redis

volumes:
  postgres_data: